version: '3'

services:
  db:
    image: postgres
    ports:
      - '5432'

  redis:
    image: redis

  sidekiq:
    build: .
    command: bundle exec sidekiq -C ./config/sidekiq.yml
    links:
      - db
      - redis
    depends_on:
      - redis

  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/async_job_service
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    links:
      - db
      - redis
    depends_on:
      - redis
      - db
      - sidekiq
