default: &default
  adapter: postgresql
  min_messages: WARNING
  pool: 5
  username: postgres
  host: db

development:
  <<: *default
  database: async_job_service_development

test:
  <<: *default
  database: async_job_service_test
